#@data/values
---
app:
  ns: "petclinic"
  name: "spring-petclinic"
  host: "petclinic.tools.azure.nvcodes.net"
  image: "harbor.tools.azure.nvcodes.net/cicd-demo/spring-petclinic:V1-b3.20210224.161029"
  wavefront:
    applicationName: "Spring-PetClinic"
    uri: "https://try.wavefront.com"
    apiToken: "da302618-124a-4e2b-9850-59b7e11ea587"
