apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: petclinic
  labels:
    app: spring-petclinic
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: aHR0cHM6Ly90cnkud2F2ZWZyb250LmNvbQ==
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: ZGEzMDI2MTgtMTI0YS00ZTJiLTk4NTAtNTliN2UxMWVhNTg3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: nitashav/spring-petclinic:V1-b18.20201106.072203
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        env:
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wavefront
              key: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
        - name: WAVEFRONT_APPLICATION_NAME
          value: Spring-PetClinic
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: petclinic
        - name: spring_profiles_active
          value: mysql
        - name: MYSQL_URL
          value: jdbc:mysql://petclinic-db-mysql/petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: petclinic
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
  - name: http
    protocol: TCP
    port: 8080
