apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: petclinic
  labels:
    app: spring-petclinic
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: aHR0cHM6Ly90cnkud2F2ZWZyb250LmNvbQ==
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: ZGEzMDI2MTgtMTI0YS00ZTJiLTk4NTAtNTliN2UxMWVhNTg3
